version: '2'
services:
  db:
    image: mysql:5.6
    networks:
      - backend
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/etc/mysql/mysql.conf.d"
      - "/tmp/mysql:/var/lib/mysql"

  flow.ci:
    image: flowci/flow.ci.backend
    networks:
      - backend
    environment:
      - FLOW_API_DOMAIN=$FLOW_API_DOMAIN
      - FLOW_WEB_DOMAIN=$FLOW_WEB_DOMAIN
      - FLOW_WS_URL=$FLOW_WS_URL
      - FLOW_SYS_EMAIL=$FLOW_SYS_EMAIL
      - FLOW_SYS_USERNAME=$FLOW_SYS_USERNAME
      - FLOW_SYS_PASSWORD=$FLOW_SYS_PASSWORD
    ports:
      - "8080:8080"
      - "2181:2181"
    depends_on:
      - db
    volumes:
      - "./docker:/etc/flow.ci/config"

  flow.web:
    image: flowci/flow.web
    networks:
      - backend
    environment:
      - FLOW_API_DOMAIN=$FLOW_API_DOMAIN
    ports:
      - "3000:80"
    depends_on:
      - flow.ci
networks:
  backend: