version: '2'
services:
  db:
    image: mysql:5.6
    networks:
      - backend
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/etc/mysql/mysql.conf.d"
      - "/tmp/mysql:/var/lib/mysql"

  flow.ci:
    image: flow.ci.backend
    networks:
      - backend
    ports:
      - "8080:8080"
      - "2181:2181"
    depends_on:
      - db
    volumes:
      - "./docker:/etc/flow.ci/config"

  flow.web:
    image: flow.web
    networks:
      - backend
    environment:
      - FLOW_API=$FLOW_API
    ports:
      - "3000:80"
    depends_on:
      - flow.ci
networks:
  backend: